In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"C:\Users\mital\Downloads\customer_churn_data.csv")
df.head()

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409-8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340-5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
2,2015,100756,372-3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
3,2015,101595,331-4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351-8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0

In [3]:
df.shape

(2000, 16)

In [4]:
df.size

32000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    2000 non-null   int64
 1   customer_id             2000 non-null   int64
 2   phone_no                2000 non-null   object
 3   gender                  1976 non-null   object
 4   age                     2000 non-null   int64
 5   no_of_days_subscribed   2000 non-null   int64
 6   multi_screen            2000 non-null   object
 7   mail_subscribed         2000 non-null   object
 8   weekly_mins_watched     2000 non-null   float64
 9   minimum_daily_mins      2000 non-null   float64
 10  maximum_daily_mins      2000 non-null   float64
 11  weekly_max_night_mins   2000 non-null   int64
 12  videos_watched          2000 non-null   int64
 13  maximum_days_inactive   1972 non-null   float64
 14  customer_support_calls  2000 non-null   int64
 15  churn                   1965 non-null   float64
dtypes: float64(5), int64(7), object(4)
memory usage: 250.1+ KB

In [6]:
df.describe(include="all")

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
count,2000.0,2000.000000,2000,1976,2000.00000,2000.000000,2000,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,1972.000000,2000.000000,1965.000000
unique,NaN,NaN,2000,2,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,409-8743,Male,NaN,NaN,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,1,1053,NaN,NaN,1802,1430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2015.0,554887.157500,NaN,NaN,38.69050,99.750000,NaN,NaN,270.178425,10.198700,30.620780,100.415500,4.482500,3.250507,1.547000,0.133333
std,0.0,261033.690318,NaN,NaN,10.20641,39.755386,NaN,NaN,80.551627,2.785519,9.129165,19.529454,2.487728,0.809084,1.315164,0.340021
min,2015.0,100198.000000,NaN,NaN,18.00000,1.000000,NaN,NaN,0.000000,0.000000,0.000000,42.000000,0.000000,0.000000,0.000000,0.000000
25%,2015.0,328634.750000,NaN,NaN,32.00000,73.000000,NaN,NaN,218.212500,8.400000,24.735000,87.000000,3.000000,3.000000,1.000000,0.000000
50%,2015.0,567957.500000,NaN,NaN,37.00000,99.000000,NaN,NaN,269.925000,10.200000,30.590000,101.000000,4.000000,3.000000,1.000000,0.000000
75%,2015.0,773280.250000,NaN,NaN,44.00000,127.000000,NaN,NaN,324.675000,12.000000,36.797500,114.000000,6.000000,4.000000,2.000000,0.000000
max,2015.0,999961.000000,NaN,NaN,82.00000,243.000000,NaN,NaN,526.200000,20.000000,59.640000,175.000000,19.000000,6.000000,9.000000,1.000000

In [7]:
df.isnull().sum()

year                       0
customer_id                0
phone_no                   0
gender                    24
age                        0
no_of_days_subscribed      0
multi_screen               0
mail_subscribed            0
weekly_mins_watched        0
minimum_daily_mins         0
maximum_daily_mins         0
weekly_max_night_mins      0
videos_watched             0
maximum_days_inactive     28
customer_support_calls     0
churn                     35
dtype: int64

In [8]:
#missing percentage
df["gender"].isnull().sum()/len(df)

0.012

In [9]:
#missing percentrage more than 30 should be dropped

In [10]:
df["gender"].dtypes

dtype('O')

In [11]:
for col in df.columns:
    if df[col].dtypes in [int,float]:
        df[col].fillna(df[col].median(),inplace = True)
    else:
        df[col].fillna(df[col].mode()[0],inplace = True)

In [12]:
df.isnull().sum()

year                      0
customer_id               0
phone_no                  0
gender                    0
age                       0
no_of_days_subscribed     0
multi_screen              0
mail_subscribed           0
weekly_mins_watched       0
minimum_daily_mins        0
maximum_daily_mins        0
weekly_max_night_mins     0
videos_watched            0
maximum_days_inactive     0
customer_support_calls    0
churn                     0
dtype: int64

In [13]:
df["phone_no"].dtypes

dtype('O')

In [14]:
df["phone_no"]=df["phone_no"].astype(str).str.replace("-"," ")

In [15]:
df

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409 8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340 5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
2,2015,100756,372 3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
3,2015,101595,331 4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351 8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2015,997132,385 7387,Female,54,75,no,yes,182.25,11.3,20.66,97,5,4.0,2,0.0
1996,2015,998086,383 9255,Male,45,127,no,no,273.45,9.3,30.99,116,3,3.0,1,0.0
1997,2015,998474,353 2080,Male,53,94,no,no,128.85,15.6,14.60,110,16,5.0,0,0.0
1998,2015,998934,359 7788,Male,40,94,no,no,178.05,10.4,20.18,100,6,3.0,3,0.0
1999,2015,999961,414 1496,Male,37,73,no,no,326.70,10.3,37.03,89,6,3.0,1,1.0

In [16]:
df["churn"].mean()

0.131

In [17]:
df["gender"].value_counts()

gender
Male      1077
Female     923
Name: count, dtype: int64

In [18]:
df["multi_screen"].value_counts()

multi_screen
no     1802
yes     198
Name: count, dtype: int64

In [19]:
#Most of the users has subscribed t0 single screen service.

In [20]:
df.groupby("gender")["no_of_days_subscribed"].mean()

gender
Female    99.826652
Male      99.684308
Name: no_of_days_subscribed, dtype: float64

In [21]:
df.groupby("gender")["videos_watched"].mean()

gender
Female    4.408451
Male      4.545961
Name: videos_watched, dtype: float64

In [22]:
#Male users has watched more videos than female users

In [23]:
df.groupby("gender")["multi_screen"].value_counts()

gender  multi_screen
Female  no              835
        yes              88
Male    no              967
        yes             110
Name: count, dtype: int64

In [24]:
df.groupby("gender")["weekly_max_night_mins"].mean()

gender
Female     99.707476
Male      101.022284
Name: weekly_max_night_mins, dtype: float64

In [25]:
#Male are the more binge behiaviour users .Male users watch the content at night.

In [26]:
df.columns

Index(['year', 'customer_id', 'phone_no', 'gender', 'age',
       'no_of_days_subscribed', 'multi_screen', 'mail_subscribed',
       'weekly_mins_watched', 'minimum_daily_mins', 'maximum_daily_mins',
       'weekly_max_night_mins', 'videos_watched', 'maximum_days_inactive',
       'customer_support_calls', 'churn'],
      dtype='object')

In [27]:
df.groupby("gender")["maximum_days_inactive"].mean()

gender
Female    3.223185
Male      3.267409
Name: maximum_days_inactive, dtype: float64

In [28]:
df.groupby("gender")["customer_support_calls"].mean()

gender
Female    1.536295
Male      1.556175
Name: customer_support_calls, dtype: float64

In [29]:
df.groupby("gender")["churn"].mean()

gender
Female    0.136511
Male      0.126277
Name: churn, dtype: float64

In [30]:
#Overall churn rate of female is more than male , i.e higher number of females has stopped using the service.

In [31]:
df["age"].value_counts()

age
36    104
38    102
35     97
37     94
34     86
     ...
77      1
82      1
80      1
76      1
79      1
Name: count, Length: 63, dtype: int64

In [32]:
# Most of the users are of Age 36

In [33]:
df["mail_subscribed"].value_counts()

mail_subscribed
no     1430
yes     570
Name: count, dtype: int64

In [34]:
#Most of the users has no subscribed to mail this indicates the engagement level .

In [35]:
df[["churn","weekly_mins_watched"]].corr()

                        churn  weekly_mins_watched
churn                1.000000             0.162876
weekly_mins_watched  0.162876             1.000000

In [36]:
df[["churn","minimum_daily_mins"]].corr()

                       churn  minimum_daily_mins
churn               1.000000            0.066646
minimum_daily_mins  0.066646            1.000000

In [37]:
df[["churn","maximum_daily_mins"]].corr()

                       churn  maximum_daily_mins
churn               1.000000            0.162874
maximum_daily_mins  0.162874            1.000000

In [38]:
#df[["no_of_days_subscribed","weekly_max_night_mins"]].corr()

In [39]:
#df[["no_of_days_subscribed","videos_watched"]].corr()

In [40]:
#df[["no_of_days_subscribed","churn"]].corr()

In [41]:
df[["videos_watched","weekly_mins_watched"]].corr()

                     videos_watched  weekly_mins_watched
videos_watched             1.000000             0.018619
weekly_mins_watched        0.018619             1.000000

In [42]:
#df[["videos_watched","minimum_daily_mins"]].corr()

In [43]:
df[["videos_watched","maximum_daily_mins"]].corr()

                    videos_watched  maximum_daily_mins
videos_watched            1.000000            0.018621
maximum_daily_mins        0.018621            1.000000

In [44]:
#df[["videos_watched","weekly_max_night_mins"]].corr()

In [45]:
#df[["weekly_mins_watched","maximum_daily_mins"]].corr()

In [46]:
df.groupby("gender")["maximum_daily_mins"].max()

gender
Female    56.83
Male      59.64
Name: maximum_daily_mins, dtype: float64

In [47]:
#Male user has spent maximum amount of time to watch content on any day in week.

In [48]:
df.groupby("gender")["weekly_mins_watched"].max()

gender
Female    501.45
Male      526.20
Name: weekly_mins_watched, dtype: float64

In [49]:
#Male user has spent maximum amount of time to watch content on in week.

In [50]:
df["weekly_mins_watched"].max()

526.2

In [51]:
df["videos_watched"].value_counts()

videos_watched
3     408
4     354
2     295
5     285
6     201
7     132
1     101
8      70
9      61
10     32
11     19
0      10
12     10
13      8
15      6
14      4
18      2
19      1
16      1
Name: count, dtype: int64

In [52]:
#Most of the users has watched the content for three days

In [53]:
df[["customer_support_calls","churn"]].corr()

                        customer_support_calls     churn
customer_support_calls                1.000000  0.204774
churn                                 0.204774  1.000000

In [54]:
df[df["customer_support_calls"] == 3]

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
3,2015,101595,331 4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
11,2015,103738,392 5296,Male,34,107,no,no,201.00,7.3,22.78,79,3,2.0,3,0.0
17,2015,107195,386 9981,Female,45,99,no,no,300.00,11.4,34.00,82,2,4.0,3,0.0
25,2015,108961,373 5732,Male,50,137,no,no,363.15,14.7,41.16,50,2,4.0,3,0.0
29,2015,111118,418 8450,Male,37,48,no,yes,346.35,7.6,39.25,87,4,3.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1979,2015,988979,392 2722,Male,38,81,no,yes,173.85,11.7,19.70,90,6,4.0,3,0.0
1982,2015,989415,394 8006,Male,25,95,no,no,234.90,12.3,26.62,115,5,4.0,3,0.0
1987,2015,991641,403 4298,Male,35,157,no,no,344.70,9.6,39.07,108,7,3.0,3,0.0
1992,2015,994954,329 3222,Female,42,119,no,yes,176.70,7.6,20.03,76,3,3.0,3,0.0
1998,2015,998934,359 7788,Male,40,94,no,no,178.05,10.4,20.18,100,6,3.0,3,0.0

In [1]:
#If the users makes more than 3 customer support calls ,then service can have high risk of churn.

In [56]:
df.groupby("multi_screen")["churn"].mean()

multi_screen
no     0.102109
yes    0.393939
Name: churn, dtype: float64

In [57]:
#If the user has multi screen plan then the service has high risk of churn

In [58]:
df[df["churn"]==True].head(3)

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
2,2015,100756,372 3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
5,2015,101953,329 6603,Male,31,65,no,no,193.65,12.7,21.95,111,6,4.0,4,1.0
7,2015,103225,348 7193,Female,40,50,no,no,196.65,5.6,22.29,88,9,3.0,5,1.0

In [59]:
df[df["churn"]==False].head(6)

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409 8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340 5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
3,2015,101595,331 4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351 8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0
6,2015,103051,416 1845,Male,54,59,no,no,239.25,10.2,27.12,106,4,3.0,0,0.0
8,2015,103408,413 4039,Male,61,205,no,yes,263.70,7.8,29.89,64,5,3.0,2,0.0

In [60]:
#If least amount of time spent by the user is smaller than the maximum amount of time spent,then the service has least risk of churn

In [61]:
#1.	Is there a significant difference in churn rate across genders?
df.groupby("gender")["churn"].mean()

gender
Female    0.136511
Male      0.126277
Name: churn, dtype: float64

In [62]:
#The churn rate female users is more than male users

In [63]:
#2.	Do customers with multi-screen access churn less often than those without it?
df.groupby("multi_screen")["churn"].mean()

multi_screen
no     0.102109
yes    0.393939
Name: churn, dtype: float64

In [64]:
#3.	What is the average age of churned vs. retained customers?
df.groupby("churn")["age"].mean()

churn
0.0    38.643843
1.0    39.000000
Name: age, dtype: float64

In [65]:
#4.	Does a longer subscription period correlate with a lower churn rate?
df.groupby("churn")["no_of_days_subscribed"].mean()

churn
0.0     99.711162
1.0    100.007634
Name: no_of_days_subscribed, dtype: float64

In [66]:
#Here the churned users actually stayed slightly longer on average.
#So, longer subscription period does not strongly correlate with lower churn in your data.

In [67]:
#4.	How does weekly watch time affect churn? Are heavy watchers less likely to churn?
df.groupby("churn")["weekly_mins_watched"].mean()

churn
0.0    265.085731
1.0    303.961260
Name: weekly_mins_watched, dtype: float64

In [68]:
#The uses who watch the content for more time in a week has high chance of getting churn.
#Because some users may leave once they consume what they want.
#Users may watch heavily during a free trial and then churn.
#Some users may watch alot then cancel.

In [80]:
#5.	Is there a consistent daily watch pattern among non-churned users?
non_churned=df[df["churn"]==False]

In [76]:
non_churned["daily variation"] = non_churned["maximum_daily_mins"]-non_churned["minimum_daily_mins"]

In [79]:
non_churned.head()

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn,daily variation
0,2015,100198,409 8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0,4.61
1,2015,100643,340 5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0,25.67
3,2015,101595,331 4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0,26.91
4,2015,101653,351 8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0,16.64
6,2015,103051,416 1845,Male,54,59,no,no,239.25,10.2,27.12,106,4,3.0,0,0.0,16.92

In [78]:
avg_variation = non_churned["daily variation"].mean()
avg_variation

19.916973532796316

In [81]:
#6.	Whether users do watch content at night tend to churn more or less?
df.groupby("churn")["weekly_max_night_mins"].mean()

churn
0.0    100.363061
1.0    100.763359
Name: weekly_max_night_mins, dtype: float64

In [82]:
#7.	How many videos does an average churned vs. non-churned customer watch per week?
df.groupby("churn")["videos_watched"].mean()

churn
0.0    4.501151
1.0    4.358779
Name: videos_watched, dtype: float64

In [83]:
#8.	Does email subscription affect churn behavior (mail_subscribed vs. churn)?
df.groupby("mail_subscribed")["churn"].mean()

mail_subscribed
no     0.147552
yes    0.089474
Name: churn, dtype: float64

In [85]:
#The users do not have  email notification are more likely to churn.

In [87]:
#9.	What is the average number of inactive days in a week for churned users?
churned =df[df["churn"]==True]
churned["maximum_days_inactive"].mean()

3.3396946564885495

In [88]:
#The users who are more likely to churn are on average inactive for 3 days in a week.

In [89]:
#10.Do users who contact customer support frequently also show lower engagement (fewer minutes/videos watched)?
df.groupby("customer_support_calls")["videos_watched"].mean()

customer_support_calls
0    4.523810
1    4.461119
2    4.486111
3    4.433071
4    4.533981
5    4.736842
6    3.363636
7    5.333333
8    6.000000
9    3.000000
Name: videos_watched, dtype: float64

In [90]:
#From the output we can see that ,the users who have call for customer support more frequently have also watched more videos .
#So we cannot say that frequent customer calls shows lower engagement.

In [91]:
#11.What is the distribution of churn among high vs. low engagement users?
df.groupby("videos_watched")["churn"].mean()

videos_watched
0     0.000000
1     0.178218
2     0.179661
3     0.117647
4     0.115819
5     0.108772
6     0.119403
7     0.136364
8     0.114286
9     0.147541
10    0.156250
11    0.157895
12    0.100000
13    0.000000
14    0.000000
15    0.500000
16    0.000000
18    0.000000
19    0.000000
Name: churn, dtype: float64

In [92]:
#The users with lower engagement are more likely to churn and users with higher engagement are less likely to churn.

In [100]:
#12.Can consistency in viewing (low difference between max and min daily minutes) reduce churn?
df["Diff_max_min_daily_min"]=df["maximum_daily_mins"]- df["minimum_daily_mins"]

In [102]:
df.groupby("churn")["Diff_max_min_daily_min"].mean()

churn
0.0    19.916974
1.0    23.772748
Name: Diff_max_min_daily_min, dtype: float64

In [103]:
#If the user watch the content consistently then the risk of user to get churn is reduced.

In [107]:
#df

In [108]:
#df.drop("Difference",axis=1)

In [109]:
#13.Are users with high peak daily watch time more loyal or more likely to churn suddenly?
df.groupby("churn")["maximum_daily_mins"].mean()

churn
0.0    30.043613
1.0    34.449466
Name: maximum_daily_mins, dtype: float64

In [112]:
#The users with maximum daily watch time are more likely to churn.
#So we can say that the users who watch content for maximum time are binge users who watch and then leave ,they are not loyal users whi stay longer.

In [115]:
#18.What is the churn rate among users with short subscriptions and long subscriptions?
df.groupby("churn")["no_of_days_subscribed"].mean()

churn
0.0     99.711162
1.0    100.007634
Name: no_of_days_subscribed, dtype: float64

In [116]:
#From the output we can say that users with long subscription are more likely to churn i.e they are not the loyal users.
#These are the users who subscibed for more days but they do not watch more content.

In [126]:
#17.Can we cluster customers into different personas based on their usage and churn behaviour? (Groupby)
a = df.groupby("churn").agg({"videos_watched":"mean","weekly_mins_watched":"mean","maximum_daily_mins":"mean" , "customer_id":"count"})
a

       videos_watched  weekly_mins_watched  maximum_daily_mins  customer_id
churn
0.0          4.501151           265.085731           30.043613         1738
1.0          4.358779           303.961260           34.449466          262

In [127]:
import matplotlib.pyplot as plt

In [139]:
gender = df.groupby("gender")["churn"].mean()
age = df["age"].head()